# Generated by Django 4.0.6 on 2022-08-05 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_slug', models.IntegerField(default=0)),
                ('blog_title', models.CharField(default='', max_length=100)),
                ('blog_sub_heading', models.CharField(default='', max_length=200)),
                ('blog_sub_heading1', models.CharField(default='', max_length=50)),
                ('blog_content', models.TextField(default='', max_length=5000)),
                ('blog_pub_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
