# Generated by Django 4.0.6 on 2022-08-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_heading',
            field=models.CharField(default='', max_length=200),
        ),
    ]
